# pod: {front: 1, web: 2, db: 4}

front:
  build: ./front
  links:
   - web
  ports:
   - "80:80"

web:
  build: ./web
  links:
   - db
  ports:
   - "80"

db:
  image: mysql
  environment:
    - "MYSQL_ROOT_PASSWORD=1234"
