front:
  build: ./front
  environment: ["affinity:pisces.kapook_web.id!=/\\d+/"]
  links:
   - web 
  ports:
   - "80:80"

web:
  build: ./web
  links:
   - db
  ports:
   - "80"

db:
  image: mysql
  environment:
    - "MYSQL_ROOT_PASSWORD=1234"
